Imports

In [1]:
from utils import sql

Exploration de la table "person"

In [7]:
visit_occurrence = sql("""
SELECT *
FROM omop.visit_occurrence
""")
visit_occurrence

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_datetime,visit_end_date,visit_end_datetime,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id,admitted_from_concept_id,admitted_from_source_value,discharged_to_concept_id,discharged_to_source_value,preceding_visit_occurrence_id
0,98894,5752,9202,1992-05-12,1992-05-12 13:05:03,1992-05-12,1992-05-12 13:40:33,32817,None,None,wellness,0,None,None,None,None,None
1,98895,5751,9202,2020-07-04,2020-07-04 21:53:23,2020-07-04,2020-07-04 22:08:23,32817,None,None,wellness,0,None,None,None,None,None
2,98896,5754,9202,2016-08-04,2016-08-04 05:01:05,2016-08-04,2016-08-04 07:58:58,32817,None,None,ambulatory,0,None,None,None,None,None
3,98897,5753,9202,2024-09-07,2024-09-07 21:46:48,2024-09-07,2024-09-07 22:01:48,32817,None,None,wellness,0,None,None,None,None,None
4,98898,5755,9202,2021-04-20,2021-04-20 23:47:47,2021-04-21,2021-04-21 00:02:47,32817,None,None,wellness,0,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5723,104617,5860,9202,2025-12-05,2025-12-05 15:00:51,2025-12-05,2025-12-05 15:32:50,32817,None,None,wellness,0,None,None,None,None,None
5724,104618,5860,9202,2025-12-19,2025-12-19 15:00:51,2025-12-19,2025-12-19 17:45:48,32817,None,None,ambulatory,0,None,None,None,None,None
5725,104619,5860,9202,2026-01-14,2026-01-14 03:00:51,2026-01-14,2026-01-14 03:15:51,32817,None,None,ambulatory,0,None,None,None,None,None
5726,104620,5860,9202,2026-01-23,2026-01-23 15:00:51,2026-01-23,2026-01-23 15:45:23,32817,None,None,outpatient,0,None,None,None,None,None
5727,104621,5860,9202,2026-02-06,2026-02-06 15:00:51,2026-02-06,2026-02-06 18:09:33,32817,None,None,ambulatory,0,None,None,None,None,None

In [8]:
visit_occurrence.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   visit_occurrence_id            5728 non-null   int64
 1   person_id                      5728 non-null   int64
 2   visit_concept_id               5728 non-null   int64
 3   visit_start_date               5728 non-null   object
 4   visit_start_datetime           5728 non-null   datetime64[ns]
 5   visit_end_date                 5728 non-null   object
 6   visit_end_datetime             5728 non-null   datetime64[ns]
 7   visit_type_concept_id          5728 non-null   int64
 8   provider_id                    0 non-null      object
 9   care_site_id                   0 non-null      object
 10  visit_source_value             5728 non-null   object
 11  visit_source_concept_id        5728 non-null   int64
 12  admitted_from_concept_id       0 non-null      object
 13  admitted_from_source_value     0 non-null      object
 14  discharged_to_concept_id       0 non-null      object
 15  discharged_to_source_value     0 non-null      object
 16  preceding_visit_occurrence_id  0 non-null      object
dtypes: datetime64[ns](2), int64(5), object(10)
memory usage: 760.9+ KB

In [10]:
visit_occurrence.describe()

,visit_occurrence_id,person_id,visit_concept_id,visit_start_datetime,visit_end_datetime,visit_type_concept_id,visit_source_concept_id
count,5728.000000,5728.000000,5.728000e+03,5728,5728,5728.0,5728.0
mean,101757.500000,5818.842004,8.514972e+04,2017-12-06 20:21:29.168645120,2017-12-07 00:44:30.572800256,32817.0,0.0
min,98894.000000,5751.000000,0.000000e+00,1930-07-06 00:13:34,1930-07-06 00:28:34,32817.0,0.0
25%,100325.750000,5793.000000,9.202000e+03,2017-10-27 23:45:43.750000128,2017-10-28 00:27:07,32817.0,0.0
50%,101757.500000,5824.000000,9.202000e+03,2020-10-12 11:51:50.500000,2020-10-12 12:29:20.500000,32817.0,0.0
75%,103189.250000,5849.000000,9.202000e+03,2023-05-22 05:31:55,2023-05-22 06:30:13,32817.0,0.0
max,104621.000000,5860.000000,4.289816e+07,2026-07-26 21:09:50,2026-07-26 21:24:50,32817.0,0.0
std,1653.675502,33.116237,1.790747e+06,NaN,NaN,0.0,0.0

In [9]:
visit_occurrence.head()

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_datetime,visit_end_date,visit_end_datetime,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id,admitted_from_concept_id,admitted_from_source_value,discharged_to_concept_id,discharged_to_source_value,preceding_visit_occurrence_id
0,98894,5752,9202,1992-05-12,1992-05-12 13:05:03,1992-05-12,1992-05-12 13:40:33,32817,None,None,wellness,0,None,None,None,None,None
1,98895,5751,9202,2020-07-04,2020-07-04 21:53:23,2020-07-04,2020-07-04 22:08:23,32817,None,None,wellness,0,None,None,None,None,None
2,98896,5754,9202,2016-08-04,2016-08-04 05:01:05,2016-08-04,2016-08-04 07:58:58,32817,None,None,ambulatory,0,None,None,None,None,None
3,98897,5753,9202,2024-09-07,2024-09-07 21:46:48,2024-09-07,2024-09-07 22:01:48,32817,None,None,wellness,0,None,None,None,None,None
4,98898,5755,9202,2021-04-20,2021-04-20 23:47:47,2021-04-21,2021-04-21 00:02:47,32817,None,None,wellness,0,None,None,None,None,None