Imports

In [1]:
from utils import sql

Exploration de la table "condition_occurrence"

In [2]:
condition_occurrence = sql("""
SELECT *
FROM omop.condition_occurrence
""")
condition_occurrence

,condition_occurrence_id,person_id,condition_concept_id,condition_start_date,condition_start_datetime,condition_end_date,condition_end_datetime,condition_type_concept_id,condition_status_concept_id,stop_reason,provider_id,visit_occurrence_id,visit_detail_id,condition_source_value,condition_source_concept_id,condition_status_source_value
0,1,5752,0,1992-05-12,1992-05-12,None,NaT,32817,None,None,None,98894,None,224295006,0,None
1,2,5752,0,1992-05-12,1992-05-12,2020-04-07,2020-04-07,32817,None,None,None,98894,None,160903007,0,None
2,3,5756,0,2016-12-29,2016-12-29,2019-07-04,2019-07-04,32817,None,None,None,98899,None,314529007,0,None
3,4,5755,0,2021-04-21,2021-04-21,2021-05-26,2021-05-26,32817,None,None,None,98898,None,314529007,0,None
4,5,5751,0,2020-07-04,2020-07-04,2020-07-04,2020-07-04,32817,None,None,None,98895,None,314529007,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3927,3928,5860,0,2025-12-05,2025-12-05,2026-01-23,2026-01-23,32817,None,None,None,104617,None,160903007,0,None
3928,3929,5860,0,2025-12-05,2025-12-05,None,NaT,32817,None,None,None,104617,None,422650009,0,None
3929,3930,5860,0,2026-01-14,2026-01-14,2026-01-23,2026-01-23,32817,None,None,None,104619,None,195662009,0,None
3930,3931,5860,0,2026-01-23,2026-01-23,None,NaT,32817,None,None,None,104620,None,160904001,0,None
3931,3932,5860,0,2026-01-23,2026-01-23,None,NaT,32817,None,None,None,104620,None,73595000,0,None

In [3]:
condition_occurrence.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3932 entries, 0 to 3931
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   condition_occurrence_id        3932 non-null   int64
 1   person_id                      3932 non-null   int64
 2   condition_concept_id           3932 non-null   int64
 3   condition_start_date           3932 non-null   object
 4   condition_start_datetime       3932 non-null   datetime64[ns]
 5   condition_end_date             2910 non-null   object
 6   condition_end_datetime         2910 non-null   datetime64[ns]
 7   condition_type_concept_id      3932 non-null   int64
 8   condition_status_concept_id    0 non-null      object
 9   stop_reason                    0 non-null      object
 10  provider_id                    0 non-null      object
 11  visit_occurrence_id            3932 non-null   int64
 12  visit_detail_id                0 non-null      object
 13  condition_source_value         3932 non-null   object
 14  condition_source_concept_id    3932 non-null   int64
 15  condition_status_source_value  0 non-null      object
dtypes: datetime64[ns](2), int64(6), object(8)
memory usage: 491.6+ KB

In [4]:
condition_occurrence.describe()

,condition_occurrence_id,person_id,condition_concept_id,condition_start_datetime,condition_end_datetime,condition_type_concept_id,visit_occurrence_id,condition_source_concept_id
count,3932.000000,3932.000000,3932.0,3932,2910,3932.0,3932.000000,3932.0
mean,1966.500000,5816.414802,0.0,2016-08-27 19:13:14.710071040,2020-08-26 20:27:12.989690880,32817.0,101593.138606,0.0
min,1.000000,5751.000000,0.0,1935-10-03 00:00:00,1970-04-20 00:00:00,32817.0,98894.000000,0.0
25%,983.750000,5792.000000,0.0,2016-10-06 12:00:00,2018-12-10 00:00:00,32817.0,100276.000000,0.0
50%,1966.500000,5822.000000,0.0,2020-05-18 12:00:00,2021-06-19 00:00:00,32817.0,101666.000000,0.0
75%,2949.250000,5846.000000,0.0,2023-06-02 00:00:00,2024-01-17 18:00:00,32817.0,102857.000000,0.0
max,3932.000000,5860.000000,0.0,2026-07-24 00:00:00,2026-07-24 00:00:00,32817.0,104620.000000,0.0
std,1135.214958,31.679481,0.0,NaN,NaN,0.0,1528.354686,0.0

In [5]:
condition_occurrence.head()

,condition_occurrence_id,person_id,condition_concept_id,condition_start_date,condition_start_datetime,condition_end_date,condition_end_datetime,condition_type_concept_id,condition_status_concept_id,stop_reason,provider_id,visit_occurrence_id,visit_detail_id,condition_source_value,condition_source_concept_id,condition_status_source_value
0,1,5752,0,1992-05-12,1992-05-12,None,NaT,32817,None,None,None,98894,None,224295006,0,None
1,2,5752,0,1992-05-12,1992-05-12,2020-04-07,2020-04-07,32817,None,None,None,98894,None,160903007,0,None
2,3,5756,0,2016-12-29,2016-12-29,2019-07-04,2019-07-04,32817,None,None,None,98899,None,314529007,0,None
3,4,5755,0,2021-04-21,2021-04-21,2021-05-26,2021-05-26,32817,None,None,None,98898,None,314529007,0,None
4,5,5751,0,2020-07-04,2020-07-04,2020-07-04,2020-07-04,32817,None,None,None,98895,None,314529007,0,None